---
title: "Conclusion"
author: "Palash Gujrathi"
date: "6/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# <p align="center"> **Conslusion** </p>

> ### Analysis and Findings


<b>
<li>The purpose of our application is to showcase how minimum wage has risen from 1968 to 2017.
CPIs have been used to stabilize the economy and protect the workers in the labor force.</li>


<li>As you can see through the graphs and significant plots, the overall minimum wage values in the United States of America increases over time.
The state with the highest mimunim wage in 2017 (the latest year given) was the District of Columbia. based on our data set. The states with the fastest increase rate in terms of minimum wage were Oregon, Washington, and District of Columbia. Washington state and California were also locations with high minumum wage values.</li>

<liYou will also notice a drastic increase in CPI values in response to the change of time. This trend has a simlar reflection when comparing different states.</li>

<li>This applictaion empowers the working class Americans to identfy job oppurnities in various locations within the United States.</li>
</b>