---
title: "README"
author: "Group 39: Shilpa, Palash, Keeke"
date: "6/5/2019"
output: html_document
---

## Link to Shiny App

https://gujrathi.shinyapps.io/INFO-201_group39/

## The Dataset

The dataset we are utilizing in this app is comprised of data pertaining to the US state minimum wages from 1968-2017. This dataset was taken from kaggle.com, and the data itself came from the US Department of Labor’s website. Within this data set, the values include year, state, values of minimum wages from each of the years mentioned, and the average consumer price index per year. As a disclaimer, we did notice that there were a couple errors in the values of the dataset itself (e.g. Alabama minimum wage was set to $0.00, which is not true), but these errors existed before we plotted the data. 

## Our Target Audience

Our target audience will be working class American citizens, as it is important for them to understand minimum wages and the trends that come along with it. It is vital to learn about minimum wage because it is a primary factor in helping to create a minimum standard of living in order to protect workers' health and well-being. The minimum wage also helps to stabilize the economy. 

## Analysis and Findings

The purpose of our application is to showcase how minimum wage has risen from 1968 to 2017.
CPIs have been used to stabilize the economy and protect the workers in the labor force.

As you can see through the graphs and significant plots, the overall minimum wage values in the United States of America increases over time.
The state with the highest mimunim wage in 2017 (the latest year given) was the District of Columbia. based on our data set. The states with the fastest increase rate in terms of minimum wage were Oregon, Washington, and District of Columbia. Washington state and California were also locations with high minumum wage values.
You will also notice a drastic increase in  CPI values in response to the change of time. This trend has a simlar reflection when comparing different states.

This applictaion empowers the working class Americans to identfy job oppurnities in various locations within the United States of America.

